name: 'Install Qt'
description: 'Install Qt on your Github Actions workflows with just one simple action'
author: 'swift-project'
branding:
  icon: 'package'
  color: 'green'
inputs:
  dir:
    description: 'Directory to install Qt'
  version:
    description: 'Version of Qt to install'
    default: '5.12.9'
  host:
    description: 'Host platform'
  target:
    description: 'Target platform for build'
    default: 'desktop'
  arch:
    description: 'Architecture for Windows/Android'
  install-deps:
    description: 'Whether or not to install Qt dependencies on Linux'
    default: 'true'
  modules:
    description: 'Additional Qt modules to install'
  mirror:
    description: 'Force a Qt mirror in case the default is not working'
  cached:
    description: "Whether or not to actually download Qt"
    default: 'false'
  aqtversion:
    description: "Version of aqtinstall to use in case of issues"
    default: '==0.9'
  py7zrversion:
    description: "Version of py7zr to use in case of issues"
    default: '==0.7'
  extra:
    description: "Any extra arguments to append to the back"
runs:
  using: 'node12'
  main: 'lib/main.js'
